routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get( '/theme/{theme}' , 'SessionController@setTheme' );
Auth::routes();

Route::post( '/payment/notify' , 'PaymentController@notify' );

Route::get( '/' , 'HomeController@index' );
Route::get( '/fat' , 'HomeController@fat' );

Route::get( '/promotion-terms' , 'HomeController@promotion_terms' );
Route::get( '/terms-of-use' , 'HomeController@terms' );
Route::get( '/privacy-policy' , 'HomeController@privacy' );
Route::post( '/createPayment' , 'PaymentController@create' ) -> name( 'create_payment' );
Route::get( '/login/{email}' , 'HomeController@login_with_email' );
Route::post( '/payment/success' , 'HomeController@payment_success' );
Route::post( '/payment/error' , 'HomeController@payment_error' );
Route::get( '/payment/{email}' , 'PaymentController@create_with_email' );

Route::group([ 'middleware' => [ 'auth' ] ] , function() {
	Route::get( '/logout' , 'HomeController@logout' ) -> name( 'logout' );
	Route::get( '/home' , 'HomeController@home' ) -> name( 'account.home' );
	Route::get( '/settings' , 'HomeController@settings' );
	Route::get( '/promotions' , 'HomeController@promotions' );
	Route::get( '/notifications' , 'HomeController@notifications' );
	Route::get( '/safe' , 'HomeController@safe' );
	Route::get( '/mission/{missionId}' , 'HomeController@mission' ) -> name( 'account.mission' );
	Route::get( '/quiz/{missionId}' , 'HomeController@quiz' ) -> name( 'account.quiz' );
	Route::get( '/section/{sectionId}' , 'HomeController@section' ) -> name( 'account.section' );
	Route::get( '/step/{stepId}' , 'HomeController@step' ) -> name( 'account.step' );
	Route::get( '/step/{stepId}/done' , 'HomeController@stepDone' ) -> name( 'account.stepDone' );
	Route::post( '/step/{stepId}/progress' , 'HomeController@stepProcess' ) -> name( 'account.stepProcess' );
	Route::post( '/register.normal' , 'HomeController@register' ) -> name( 'register_normal' );
	Route::post( '/register.try' , 'HomeController@register_try' ) -> name( 'register_try' );
	Route::get( '/safe/save/{id}/{type}' , 'SafeController@save' ) -> name( 'safe.save' );
	Route::post( '/settings' , 'HomeController@save_settings' ) -> name( 'settings.save' );
});
Route::get( '/admin/sms' , 'Admin\SMSController@index' ) -> name( 'admin.sms' );
Route::post( '/admin/check_sms' , 'Admin\SMSController@check' ) -> name( 'admin.check_sms' );
Route::get( '/admin/login' , 'Admin\MainController@login' ) -> name( 'admin.login' );
Route::post( '/admin/login' , 'Admin\MainController@loginPost' ) -> name( 'admin.loginPost' );
Route::group([ 'middleware' => [ 'auth' ] ] , function() {
	Route::get( '/logout' , 'Admin\MainController@logout' ) -> name( 'logout' );
});
Route::group([ 'middleware' => [ 'auth' , 'App\Http\Middleware\Admin' ] , 'prefix' => 'admin' ] , function() {
	Route::get( '/' , 'Admin\MainController@index' ) -> name( 'admin.index' );
	Route::get( '/canceled' , 'Admin\MainController@canceled_transactions' ) -> name( 'admin.canceled_transactions' );
	Route::post( '/transaction/status/{id}' , 'Admin\MainController@transactionStatus' );
	Route::get( '/users' , 'Admin\UserController@index' ) -> name( 'admin.users' );
	Route::get( '/tickets' , 'Admin\ChatController@index' ) -> name( 'admin.tickets' );
	Route::post( '/proxies/upload' , 'Admin\ProxyController@upload' ) -> name( 'proxies.upload' );
	Route::post( '/proxies/store' , 'Admin\ProxyController@store' ) -> name( 'proxies.store' );
	Route::resources([
		'admin_missions' => 'Admin\MissionController',
		'admin_sections' => 'Admin\SectionController',
		'admin_steps' => 'Admin\StepController',
		'admin_quizzes' => 'Admin\QuizController',
		'admin_questions' => 'Admin\QuestionController',
		'proxies' => 'Admin\ProxyController',
		'settings' => 'Admin\SettingController',
		'currency_groups' => 'Admin\CurrencyGroupController',
		'reviews' => 'Admin\ReviewController'
	]);
	Route::get( '/admin_sections/mission/{mission_id}' , 'Admin\SectionController@index_mission' ) -> name( 'admin_sections.mission' );
	Route::get( '/admin_steps/mission/{mission_id}' , 'Admin\StepController@index_mission' ) -> name( 'admin_steps.mission' );
	Route::get( '/admin_steps/section/{section_id}' , 'Admin\StepController@index_section' ) -> name( 'admin_steps.section' );
	Route::get( '/admin_steps/delete/{id}' , 'Admin\StepController@delete' ) -> name( 'admin_steps.delete' );
	Route::get( '/admin_quizzes/delete/{id}' , 'Admin\QuizController@delete' ) -> name( 'admin_quizzes.delete' );
	Route::get( '/admin_questions/delete/{id}' , 'Admin\QuestionController@delete' ) -> name( 'admin_questions.delete' );
	Route::get( '/admin_questions/quiz/{quiz_id}' , 'Admin\QuestionController@index_quiz' ) -> name( 'admin_questions.quiz' );
	Route::get( '/admin_missions/delete/{id}' , 'Admin\MissionController@delete' ) -> name( 'admin_missions.delete' );
	Route::get( '/admin_sections/delete/{id}' , 'Admin\SectionController@delete' ) -> name( 'admin_sections.delete' );
	Route::get( '/admin_payments' , 'Admin\PaymentController@index' ) -> name( 'admin_payments.index' );
	Route::get( '/reviews/publish/{id}' , 'Admin\ReviewController@publish' ) -> name( 'reviews.publish' );
});

Route::get( 'testemail' , 'HomeController@testemail' );

app/Mission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mission extends Model
{
    //
    protected $guarded = [];
	public function sections () {
		return $this -> hasMany( 'App\Section', 'mission_id' , 'id' ) -> orderBy( 'order' );
	}
	public function quiz () {
		return $this -> hasOne( 'App\Quiz', 'mission_id' , 'id' );
	}
	public function steps () {
		return $this -> hasManyThrough( 'App\Step' , 'App\Section' , 'mission_id' , 'section_id' , 'id' , 'id' ) -> orderBy( 'order' );
	}
	public function stepCount () {
		return $this -> steps() -> count();
	}
}

app/Http/Controllers/Admin/MissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
// use Illuminate\Http\Request;
use App\Helpers\FileHelper;
use App\Mission;
// use App\Helpers\ExchangeHelper;
use App\Http\Requests\Admin\Mission as Request;

class MissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index () {
        $missions = Mission::orderBy( 'id' , "DESC" ) -> paginate( 30 );
        $data = [
            'title' => 'Миссии',
            'missions' => $missions
        ];
        return view( 'admin.missions.index' , $data );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create () {
        $data = [
            'title' => 'Добавление миссии',
        ];
        return view( 'admin.missions.create' , $data );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store ( Request $req ) {
        $file = $req -> file( 'file' );
        $fileInfo = FileHelper::upload( $file , env( 'MISSION_ICONS_PATH' ) );
        $input = $req -> except( 'file' , '_token' , '_method' );
        $input[ 'img_url' ] = env( "MISSION_ICONS_PUBLIC_PATH" ) . $fileInfo[ 'title' ];
        $input[ 'img_path' ] = $fileInfo[ 'path' ];
        Mission::create( $input );
        OrderHelper::orderAll();
        return redirect() -> route( 'admin_missions.index' ) -> withStatus( 'Миссия успешно добавлена' );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit ( $id ) {
    	$mission = Mission::findOrFail( $id );
        $data = [
            'title' => 'Изменение миссии',
            'mission' => $mission,
        ];
        return view( 'admin.missions.edit' , $data );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update ( Request $req , $id ) {
        $input = $req -> except( 'file' , '_token' , '_method' );
        if ( $req -> has( 'file' ) ) {
            $file = $req -> file( 'file' );
	        $fileInfo = FileHelper::upload( $file , env( 'MISSION_ICONS_PATH' ) );
	        $input[ 'img_url' ] = env( "MISSION_ICONS_PUBLIC_PATH" ) . $fileInfo[ 'title' ];
	        $input[ 'img_path' ] = $fileInfo[ 'path' ];
        }
        Mission::whereId( $id ) -> update( $input );
        return redirect() -> back() -> withStatus( 'Изменения сохранены' );
        OrderHelper::orderAll();
        return redirect() -> route( 'admin_missions.index' ) -> withStatus( 'Миссия успешно изменена' );




    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete ( $id ) {
        Mission::findOrFail( $id ) -> delete();
        OrderHelper::orderAll();
        return redirect() -> route( 'admin_missions.index' ) -> withStatus( 'Миссия успешно удалена' );
    }
}

resources/views/admin/missions/create.blade.php
@extends( 'layouts.admin' )
@section( 'content' )

<div class="container-fluid">
	<h1 class="mb-4">{{ $title }}</h1>
	@if ($errors->any())
		@foreach ($errors->all() as $error)
			<div class="alert alert-danger">{{$error}}</div>
		@endforeach
	@endif

	<form class="form" action="{{ route( 'admin_missions.store' ) }}" enctype="multipart/form-data" method="POST">
		@csrf
		<div class="form-group">
			<label>Название</label>
			<input autofocus="" class="form-control" type="text" required="" name="title" value="{{ old( 'title' ) }}" />
		</div>
		<div class="form-group">
			<label>Описание</label>
			<textarea minlength="10" name="description" class="form-control">{{ old( 'description' ) }}</textarea>
		</div>
		<div class="form-group">
			<label>Порядок</label>
			<input class="form-control" type="number" required="" name="order" value="{{ old( 'order' ) }}" />
		</div>
		<div class="form-group text-center d-none" id="thumbnail-wrapper">
			<img width="200" id="upload-thumbnail" />
		</div>
		<div class="form-group">
			<div class="custom-file">
				<input required="" type="file" name="file"  accept="image/*" class="custom-file-input" id="img-upload" />
				<label class="custom-file-label" for="img-upload">Файл</label>
			</div>
		</div>
		<div class="form-group">
			<button class="btn btn-block btn-primary">Создать</button>
		</div>
	</form>
</div>
@endsection

resources/views/admin/missions/edit.blade.php
@extends( 'layouts.admin' )
@section( 'content' )

<div class="container-fluid">
	<h1 class="mb-4">{{ $title }} #{{ $mission -> id }}</h1>
	@if ($errors->any())
		@foreach ($errors->all() as $error)
			<div class="alert alert-danger">{{$error}}</div>
		@endforeach
	@endif

    @if ( session( 'status' ) )
        <p class="alert alert-success">{{ session( 'status' ) }}</p>
    @endif
	<form class="form" action="{{ route( 'admin_missions.update' , $mission -> id ) }}" enctype="multipart/form-data" method="POST">
		@csrf
		@method( 'PUT' )
		<input type="hidden" name="id" value="{{ $mission -> id }}" />
		<div class="form-group">
			<label>Название</label>
			<input autofocus="" class="form-control" type="text" required="" name="title" value="{{ $mission -> title }}" />
		</div>
		<div class="form-group">
			<label>Описание</label>
			<textarea minlength="10" name="description" class="form-control">{{ $mission -> description }}</textarea>
		</div>
		<div class="form-group">
			<label>Порядок</label>
			<input class="form-control" type="number" required="" name="order" value="{{ $mission -> order }}" />
		</div>
		<div class="form-group text-center" id="thumbnail-wrapper">
			<img width="200" id="upload-thumbnail" src="{{ $mission -> img_url }}" />
		</div>
		<div class="form-group">
			<div class="custom-file">
				<input type="file" name="file"  accept="image/*" class="custom-file-input" id="img-upload" />
				<label class="custom-file-label" for="img-upload">Choose file</label>
			</div>
		</div>
		<div class="form-group">
			<button class="btn btn-block btn-primary">Сохранить</button>
		</div>
	</form>
</div>
@endsection

resources/views/admin/missions/index.blade.php
@extends( 'layouts.admin' )
@section( 'content' )

<div class="container-fluid">
	<h1 class="mb-4">{{ $title }}</h1>
    @if ( session( 'status' ) )
        <p class="alert alert-success">{{ session( 'status' ) }}</p>
    @endif
	<a href="{{ route( 'admin_missions.create' ) }}" class="mb-3 btn btn-xl btn-info"><i class="fa fa-plus"></i> Добавить</a>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>
					ID
				</th>
				<th>
					Название
				</th>
				<th>
					Картинка
				</th>
				<th>
					Описание
				</th>
				<th>
					Порядок
				</th>
				<th>
					Изменено
				</th>
				<th>
					<i class="fa fa-wrench"></i>
				</th>
			</tr>
		</thead>
		<tbody>
			@foreach( $missions as $mission )
				<tr>
					<td>{{ $mission -> id }}</td>
					<td>{{ $mission -> title }}</td>
					<td>
						<img src="{{ $mission -> img_url }}" width="75" />
					</td>
					<td>{{ $mission -> description }}</td>
					<td>{{ $mission -> order }}</td>
					<td>{{ date( 'Y-m-d H:i' , strtotime( $mission -> updated_at ) ) }}</td>
					<td>
						<a class="btn btn-sm btn-info" href="{{ route( 'admin_sections.mission' , $mission -> id ) }}"><i class="fa fa-eye"></i> Секции <sup>{{ $mission -> sections() -> count() }}</sup></a>
						<a class="btn btn-sm btn-info" href="{{ route( 'admin_steps.mission' , $mission -> id ) }}"><i class="fa fa-eye"></i> Шаги <sup>{{ $mission -> steps() -> count() }}</sup></a>
						<a class="btn btn-sm btn-warning" href="{{ route( 'admin_missions.edit' , $mission -> id ) }}"><i class="fa fa-edit"></i></a>
						<a class="btn btn-sm btn-danger" onClick="return confirm( 'Вы уверены?' );" href="{{ route( 'admin_missions.delete' , $mission -> id ) }}"><i class="fa fa-trash"></i></a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
	<div>
		{{ $missions -> links() }}
	</div>
</div>
@endsection