routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get( '/theme/{theme}' , 'SessionController@setTheme' );
Auth::routes();

Route::post( '/payment/notify' , 'PaymentController@notify' );

Route::get( '/' , 'HomeController@index' );
Route::get( '/fat' , 'HomeController@fat' );

Route::get( '/promotion-terms' , 'HomeController@promotion_terms' );
Route::get( '/terms-of-use' , 'HomeController@terms' );
Route::get( '/privacy-policy' , 'HomeController@privacy' );
Route::post( '/createPayment' , 'PaymentController@create' ) -> name( 'create_payment' );
Route::get( '/login/{email}' , 'HomeController@login_with_email' );
Route::post( '/payment/success' , 'HomeController@payment_success' );
Route::post( '/payment/error' , 'HomeController@payment_error' );
Route::get( '/payment/{email}' , 'PaymentController@create_with_email' );

Route::group([ 'middleware' => [ 'auth' ] ] , function() {
	Route::get( '/logout' , 'HomeController@logout' ) -> name( 'logout' );
	Route::get( '/home' , 'HomeController@home' ) -> name( 'account.home' );
	Route::get( '/settings' , 'HomeController@settings' );
	Route::get( '/promotions' , 'HomeController@promotions' );
	Route::get( '/notifications' , 'HomeController@notifications' );
	Route::get( '/safe' , 'HomeController@safe' );
	Route::get( '/mission/{missionId}' , 'HomeController@mission' ) -> name( 'account.mission' );
	Route::get( '/quiz/{missionId}' , 'HomeController@quiz' ) -> name( 'account.quiz' );
	Route::get( '/section/{sectionId}' , 'HomeController@section' ) -> name( 'account.section' );
	Route::get( '/step/{stepId}' , 'HomeController@step' ) -> name( 'account.step' );
	Route::get( '/step/{stepId}/done' , 'HomeController@stepDone' ) -> name( 'account.stepDone' );
	Route::post( '/step/{stepId}/progress' , 'HomeController@stepProcess' ) -> name( 'account.stepProcess' );
	Route::post( '/register.normal' , 'HomeController@register' ) -> name( 'register_normal' );
	Route::post( '/register.try' , 'HomeController@register_try' ) -> name( 'register_try' );
	Route::get( '/safe/save/{id}/{type}' , 'SafeController@save' ) -> name( 'safe.save' );
	Route::post( '/settings' , 'HomeController@save_settings' ) -> name( 'settings.save' );
});
Route::get( '/admin/sms' , 'Admin\SMSController@index' ) -> name( 'admin.sms' );
Route::post( '/admin/check_sms' , 'Admin\SMSController@check' ) -> name( 'admin.check_sms' );
Route::get( '/admin/login' , 'Admin\MainController@login' ) -> name( 'admin.login' );
Route::post( '/admin/login' , 'Admin\MainController@loginPost' ) -> name( 'admin.loginPost' );
Route::group([ 'middleware' => [ 'auth' ] ] , function() {
	Route::get( '/logout' , 'Admin\MainController@logout' ) -> name( 'logout' );
});
Route::group([ 'middleware' => [ 'auth' , 'App\Http\Middleware\Admin' ] , 'prefix' => 'admin' ] , function() {
	Route::get( '/' , 'Admin\MainController@index' ) -> name( 'admin.index' );
	Route::get( '/canceled' , 'Admin\MainController@canceled_transactions' ) -> name( 'admin.canceled_transactions' );
	Route::post( '/transaction/status/{id}' , 'Admin\MainController@transactionStatus' );
	Route::get( '/users' , 'Admin\UserController@index' ) -> name( 'admin.users' );
	Route::get( '/tickets' , 'Admin\ChatController@index' ) -> name( 'admin.tickets' );
	Route::post( '/proxies/upload' , 'Admin\ProxyController@upload' ) -> name( 'proxies.upload' );
	Route::post( '/proxies/store' , 'Admin\ProxyController@store' ) -> name( 'proxies.store' );
	Route::resources([
		'admin_missions' => 'Admin\MissionController',
		'admin_sections' => 'Admin\SectionController',
		'admin_steps' => 'Admin\StepController',
		'admin_quizzes' => 'Admin\QuizController',
		'admin_questions' => 'Admin\QuestionController',
		'proxies' => 'Admin\ProxyController',
		'settings' => 'Admin\SettingController',
		'currency_groups' => 'Admin\CurrencyGroupController',
		'reviews' => 'Admin\ReviewController'
	]);
	Route::get( '/admin_sections/mission/{mission_id}' , 'Admin\SectionController@index_mission' ) -> name( 'admin_sections.mission' );
	Route::get( '/admin_steps/mission/{mission_id}' , 'Admin\StepController@index_mission' ) -> name( 'admin_steps.mission' );
	Route::get( '/admin_steps/section/{section_id}' , 'Admin\StepController@index_section' ) -> name( 'admin_steps.section' );
	Route::get( '/admin_steps/delete/{id}' , 'Admin\StepController@delete' ) -> name( 'admin_steps.delete' );
	Route::get( '/admin_quizzes/delete/{id}' , 'Admin\QuizController@delete' ) -> name( 'admin_quizzes.delete' );
	Route::get( '/admin_questions/delete/{id}' , 'Admin\QuestionController@delete' ) -> name( 'admin_questions.delete' );
	Route::get( '/admin_questions/quiz/{quiz_id}' , 'Admin\QuestionController@index_quiz' ) -> name( 'admin_questions.quiz' );
	Route::get( '/admin_missions/delete/{id}' , 'Admin\MissionController@delete' ) -> name( 'admin_missions.delete' );
	Route::get( '/admin_sections/delete/{id}' , 'Admin\SectionController@delete' ) -> name( 'admin_sections.delete' );
	Route::get( '/admin_payments' , 'Admin\PaymentController@index' ) -> name( 'admin_payments.index' );
	Route::get( '/reviews/publish/{id}' , 'Admin\ReviewController@publish' ) -> name( 'reviews.publish' );
});

Route::get( 'testemail' , 'HomeController@testemail' );

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@isset( $title ) {{ $title }} @else {{ config('app.name', 'Laravel') }} @endisset</title>

    <!-- Scripts -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" type="image/png" href="favicon.png" />
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700&display=swap&subset=cyrillic,cyrillic-ext" rel="stylesheet">
    <!-- <link rel="stylesheet" type="text/css" href="/chat.css" /> -->
    <!-- Styles -->
    <link href="{{ asset('admin.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark text-light shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url('/admin') }}">
                    <img src="/logo.png" width="75" class="logo" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @auth
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route( 'admin_missions.index' ) }}">
                                    Миссии
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route( 'admin_sections.index' ) }}">
                                    Секции
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route( 'admin_steps.index' ) }}">
                                    Шаги
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Тесты <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-center" href="{{ route( 'admin_quizzes.index' ) }}">
                                        Тесты
                                    </a>
                                    <a class="dropdown-item text-center" href="{{ route( 'admin_questions.index' ) }}">
                                        Вопросы
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route( 'settings.index' ) }}">
                                    Настройки
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route( 'admin.users' ) }}">
                                    Пользователи
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route( 'admin_payments.index' ) }}">
                                    Оплаты
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user() -> name ? Auth::user() -> name : 'Admin' }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-center" href="{{ route( 'logout' ) }}">
                                        <i style="font-size: 20px;" class="fa fa-sign-out"></i>
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                    </ul>
                </div>
                @endauth
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="{{ asset( 'admin.js' ) }}" defer></script>
    @yield( 'scripts' )
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace( '_' , '-' , app() -> getLocale() ) }}">
<head>
    @include( 'partials.head' )
    @yield( 'head' )
</head>
<body id="{{ Cookie::get( 'theme' ) !== null && Cookie::get( 'theme' ) == 'theme-light' ? 'theme-light' : 'theme-light' }}">
    <div id="app" class="pb-5 pb-md-1">
        @include( 'partials.header' )
            <main class="">
                <section class="intro-section py-3 py-md-5">
                    <div class="container-fluid">
                        @yield( 'pre_content' )
                        <div class="row">
                            @include( 'partials.sidebar' )
                            <div class="col-lg-9 px-3 px-md-3">
                                @yield( 'content' )
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        @include( 'partials.footer' )
    </div>
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @yield( 'scripts' )
</body>

resources/views/layouts/home.blade.php
<!doctype html>
<html lang="{{ str_replace( '_' , '-' , app() -> getLocale() ) }}">
<head>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Speakland</title>
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link href="/landing/css/styles.css" rel="stylesheet" />
        @yield( 'head' )
    </head>
</head>
<body id="page-top">
    <div id="app">
        @include( 'partials.home.header' )
            <main class="">
                @yield( 'content' )
            </main>
        @include( 'partials.home.footer' )
        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
        <div class="scroll-to-top d-lg-none position-fixed">
            <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a>
        </div>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" defer="" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" defer=""></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" defer=""></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js" defer=""></script>
    <!-- Core theme JS-->
    <script src="/landing/js/scripts.js" defer=""></script>
    @yield( 'scripts' )
</body>

resources/views/layouts/login.blade.php
<!doctype html>
<html lang="{{ str_replace( '_' , '-' , app() -> getLocale() ) }}">
<head>
    @include( 'partials.head' )
    @yield( 'head' )
</head>
<body id="{{ Cookie::get( 'theme' ) !== null && Cookie::get( 'theme' ) == 'theme-light' ? 'theme-light' : 'theme-light' }}">
    <div id="app" class="pb-5 pb-md-1">
        @yield( 'content' )
        @include( 'partials.footer' )
    </div>
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @yield( 'scripts' )
</body>

resources/views/layouts/poxudenie.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@isset( $title ) {{ $title }} @else {{ config('app.name', 'Laravel') }} @endisset</title>

    <!-- Scripts -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" type="image/png" href="favicon.png" />
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700&display=swap&subset=cyrillic,cyrillic-ext" rel="stylesheet">
    <!-- <link rel="stylesheet" type="text/css" href="/chat.css" /> -->
    <!-- Styles -->
    <link href="{{ asset('admin.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="{{ asset( 'admin.js' ) }}" defer></script>
    @yield( 'scripts' )
</body>
</html>